"""add auth sessions & refresh tokens

Revision ID: b791a564d5ca
Revises: 7d26f38611c7
Create Date: 2025-08-12 00:18:14.796772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b791a564d5ca'
down_revision: Union[str, Sequence[str], None] = '7d26f38611c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authsessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Enum('USER_LOGOUT', 'REUSE_DETECTED', 'ADMIN_FORCE', 'PASSWORD_CHANGE', 'ROTATED', name='revoke_reason_enum'), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_auth_sessions_last_seen', 'authsessions', ['last_seen_at'], unique=False)
    op.create_index('ix_auth_sessions_user', 'authsessions', ['user_id'], unique=False)
    op.create_table('refreshtokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Enum('USER_LOGOUT', 'REUSE_DETECTED', 'ADMIN_FORCE', 'PASSWORD_CHANGE', 'ROTATED', name='revoke_reason_enum'), nullable=True),
    sa.Column('replaced_by_jti', sa.UUID(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_family', 'refreshtokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_session', 'refreshtokens', ['session_id'], unique=False)
    op.create_index('ix_refresh_tokens_user', 'refreshtokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refreshtokens_family_id'), 'refreshtokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refreshtokens_session_id'), 'refreshtokens', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_session_id'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_family_id'), table_name='refreshtokens')
    op.drop_index('ix_refresh_tokens_user', table_name='refreshtokens')
    op.drop_index('ix_refresh_tokens_session', table_name='refreshtokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refreshtokens')
    op.drop_table('refreshtokens')
    op.drop_index('ix_auth_sessions_user', table_name='authsessions')
    op.drop_index('ix_auth_sessions_last_seen', table_name='authsessions')
    op.drop_table('authsessions')
    # ### end Alembic commands ###
