class UserNotFoundError(Exception): ...


class EmailAlreadyUsedError(Exception): ...


class WrongPasswordError(Exception): ...


class CurrentUserNotFoundError(Exception): ...


class UserInactiveError(Exception): ...
